### ISSUE TITLE
[Task] Heads up for PEP 594 and support Python 3.13

### ISSUE THREAD

**Issue by nandgator** [twisted/twisted#11750]
## Ref: [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/)

**Is your feature request related to a problem? Please describe.**

PEP 594 is accepted. Deprecation warning is rolling out from Python 3.11.

```
====================================================================================== test session starts =======================================================================================
platform linux -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0
rootdir: ~/my-project
plugins: anyio-3.6.2, Faker-15.2.0
collected 5 items                                                                                                                                                                                

tests/test_utils.py .....                                                                                                                                                                  [100%]

======================================================================================== warnings summary ========================================================================================
../../../../../.cache/pypoetry/virtualenvs/venv-6o_5W4s2-py3.11/lib/python3.11/site-packages/twisted/web/http.py:103
  ~/.cache/pypoetry/virtualenvs/venv-6o_5W4s2-py3.11/lib/python3.11/site-packages/twisted/web/http.py:103: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================== 5 passed, 1 warning in 2.16s ==================================================================================
```

**Describe the solution you'd like**

Twisted is using [`crypt`](https://github.com/twisted/twisted/search?q=%22import+crypt%22) [`spwd`](https://github.com/twisted/twisted/search?q=%22import+spwd%22) and [`cgi`](https://github.com/twisted/twisted/search?p=2&q=%22import+cgi%22). Create a task to clean up these libraries.

---------

Python 3.13.0 beta 1 is scheduled for 2024-05-07 with final release 3.13.0 2024-10-01

Todo for 3.13, listed in priority order

* [x] Remove cgi and html #12015
* [x] Remove cgi multipart parsing #12058
* [x] util.getPassword #12060
* [x] builtins.TypeError: '<' not supported between instances of 'NoneType' and 'int' - https://github.com/twisted/twisted/issues/12056
* [x] Update docstring formatting https://github.com/twisted/twisted/issues/12063
* [x] defer.inlineCallbacks exception traceback formating https://github.com/twisted/twisted/issues/12061
* [x] twisted.internet.utils https://github.com/twisted/twisted/issues/12062
* [x] builtins.TypeError: code() argument 13 must be str, not int - This is from automat 
* [x] #12098
* [x] #12194
* [x] #12290
* [ ] Windows runners in CI: currently blocked by lack of pywin32 wheels for 3.13 . [Upstream report](https://github.com/mhammond/pywin32/issues/2367)
* [x] Remove crypt #11826

**Comment by adiroiban** [comment]
There is a PR waiting to be reviewd for CGI - https://github.com/twisted/twisted/pull/12016

**Comment by nandgator** [comment]
Ah I see, someone could link it to this issue.

**Comment by adiroiban** [comment]
Hi.

Thanks for the report.

For reference

> PEP 594: dead batteries - The remaining 19 “dead batteries” have been removed from the standard library: aifc, audioop, cgi, cgitb, chunk, crypt, imghdr, mailcap, msilib, nis, nntplib, ossaudiodev, pipes, sndhdr, spwd, sunau, telnetlib, uu and xdrlib.

This ticket can continue to stay open I we also need to handle `spwd` and `crypt`

https://github.com/twisted/twisted/pull/12016 only handles the `cgi` part.

There is also this ticket related to `crypt` https://github.com/twisted/twisted/issues/11826

I think that this ticket should be closed only once Twisted tests pass on Python 3.13

**Comment by adiroiban** [comment]
3.13 alpha is availabe on GitHub action, so we an create a PR and see what else is missing 

```
    - uses: actions/setup-python@v4
     with:
       python-version: 3.13.0-alpha.1
```
------

I now see there is 3.13 alpha build available on GitHub https://github.com/actions/python-versions/releases/tag/3.13.0-alpha.2-6966007093

**Comment by adiroiban** [comment]
I will use this ticket as the meta-ticket for all work needed to get support for Python 3.13

**Comment by itamarst** [comment]
Did a bit of testing, and:

1. Cython doesn't work with 3.13a4, which means cython-test-exception-raiser can't be installed.
2. This was apparently due to change in 3.13 that was since reverted. So when next 3.13 alpha release happens it might be easier to make progress on some of the tickets.
